language: java
service:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE lieordiedb;'
  - mysql -e "CREATE USER 'nutzer'@'localhost' IDENTIFIED BY '1234';"
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'nutzer'@'localhost';"
  - sudo service mysql restart