version: "3.1"
services:
  proxy:
    image: nginx:1.15-alpine
    ports:
      - "8080:80"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
    depends_on:
      - projekt
      - projektdb

  projekt:
    build: dieOrLie-ac
    image: dieOrLie-ac
    environment:
      - DB_HOST=lieordiedb
      - DB_USER=nutzer
      - DB_PASSWORD=1234
      - DB_DATABASE=lieordiedb-ac
    depends_on:
      - projektdb
    links:
      - projektdb

  lieordiedb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=nutzer
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=lieordiedb-ac

    propay:
      image: propra/propay
      ports:
        - "8888:8888"
      # Optional
      volumes:
        - ./data:/code/data

  # ========================================